@ Generated by gcc 2.95.2 19991024 (release) for ARM/elf
	.file	"compr_rubin.c"
gcc2_compiled.:
	.ident	"$Id: compr_rubin.s,v 1.1 2001/08/14 21:17:39 jamey Exp $"
.text
	.align	2
	.global	rubin_do_decompress
	.type	 rubin_do_decompress,function
rubin_do_decompress:
	@ args = 0, pretend = 0, frame = 4
	@ frame_needed = 0, current_function_anonymous_args = 0
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, lr}
	mov	r8, r1
	mov	r6, r2
	mov	ip, #16
	mov	lr, #0
	sub	sp, sp, #4
	ldrb	r2, [r8, #0]	@ zero_extendqisi2
	add	r3, r6, r3
	str	r3, [sp, #0]
	mov	r5, #65536
	ldr	r1, [sp, #0]
	mov	r9, r0
	ldrb	r3, [r8, #1]	@ zero_extendqisi2
	cmp	r6, r1
	orr	r1, r3, r2, asl #8
	ldr	r7, [r8, #0]
	bcs	.L4
.L5:
	and	ip, ip, #255
	cmp	ip, #1792
	add	r0, r6, #1
	bhi	.L7
.L9:
	tst	lr, #32768
	mov	r4, r4, lsr #1
	b	.L19
.L12:
	bic	lr, lr, #32768
	mov	lr, lr, asl #1
	mov	r5, r5, asl #1
	bic	r1, r1, #32768
	eor	r3, ip, #7
	and	r3, r3, #255
	mov	r3, r7, lsr r3
	and	r3, r3, #1
	orr	r1, r3, r1, asl #1
	add	ip, ip, #1
	cmp	ip, #31
	bichi	ip, ip, #255
	ldrhi	r7, [r8, #4]!
.L10:
	tst	lr, #32768
.L19:
	bne	.L12
	add	r3, r5, lr
	cmp	r3, #32768
	bls	.L12
	ldrb	r2, [r9, ip, lsr #8]	@ zero_extendqisi2
	mul	r3, r5, r2
	mov	r3, r3, lsr #8
	add	r2, lr, r3
	cmp	r1, r2
	movcc	r5, r3
	bcc	.L8
.L15:
	orr	r4, r4, #128
	rsb	r5, r3, r5
	mov	lr, r2
.L8:
	add	ip, ip, #256
	cmp	ip, #1792
	bls	.L9
.L7:
	strb	r4, [r6, #0]
	ldr	r3, [sp, #0]
	mov	r6, r0
	cmp	r6, r3
	bcc	.L5
.L4:
	add	sp, sp, #4
	ldmfd	sp!, {r4, r5, r6, r7, r8, r9, pc}
.Lfe1:
	.size	 rubin_do_decompress,.Lfe1-rubin_do_decompress
	.align	2
	.global	dynrubin_decompress
	.type	 dynrubin_decompress,function
dynrubin_decompress:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 0, current_function_anonymous_args = 0
	stmfd	sp!, {r4, lr}
	mov	ip, r0
	mov	r2, r1
	mov	r4, r3
	mov	r1, #0
	sub	sp, sp, #8
	mov	r0, sp
	mov	lr, r0
.L24:
	ldrb	r3, [ip, r1]
	rsb	r3, r3, #0
	strb	r3, [lr, r1]
	add	r1, r1, #1
	cmp	r1, #7
	ble	.L24
	add	r1, ip, #8
	mov	r3, r4
	bl	rubin_do_decompress(PLT)
	add	sp, sp, #8
	ldmfd	sp!, {r4, pc}
.Lfe2:
	.size	 dynrubin_decompress,.Lfe2-dynrubin_decompress
	.ident	"GCC: (GNU) 2.95.2 19991024 (release)"
